/**
 * Permission Definitions - SSOT
 * All application permissions in one place
 */

import { PERMISSIONS, type Permission } from '@/config';

export { PERMISSIONS, type Permission };

/**
 * Permission groups for easier management
 */
export const PERMISSION_GROUPS = {
  CONTENT: [
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_EDIT_OWN,
    PERMISSIONS.CONTENT_EDIT_ANY,
    PERMISSIONS.CONTENT_DELETE_OWN,
    PERMISSIONS.CONTENT_DELETE_ANY,
    PERMISSIONS.CONTENT_MODERATE,
  ],
  USER: [
    PERMISSIONS.USER_VIEW_PUBLIC,
    PERMISSIONS.USER_VIEW_PROFILE,
    PERMISSIONS.USER_EDIT_PROFILE,
    PERMISSIONS.USER_MANAGE_ANY,
  ],
  SOCIAL: [
    PERMISSIONS.SOCIAL_COMMENT,
    PERMISSIONS.SOCIAL_LIKE,
    PERMISSIONS.SOCIAL_SHARE,
    PERMISSIONS.SOCIAL_FOLLOW,
    PERMISSIONS.SOCIAL_MESSAGE,
  ],
  GAMIFICATION: [
    PERMISSIONS.GAMIFICATION_VIEW,
    PERMISSIONS.GAMIFICATION_EARN,
    PERMISSIONS.GAMIFICATION_REDEEM,
  ],
  ADMIN: [
    PERMISSIONS.ADMIN_DASHBOARD,
    PERMISSIONS.ADMIN_USERS,
    PERMISSIONS.ADMIN_CONTENT,
    PERMISSIONS.ADMIN_ANALYTICS,
    PERMISSIONS.ADMIN_SETTINGS,
    PERMISSIONS.ADMIN_SECURITY,
    PERMISSIONS.ADMIN_MONITORING,
  ],
  CONTRIBUTOR: [
    PERMISSIONS.CONTRIBUTOR_APPLY,
    PERMISSIONS.CONTRIBUTOR_DASHBOARD,
    PERMISSIONS.CONTRIBUTOR_EARNINGS,
    PERMISSIONS.CONTRIBUTOR_ANALYTICS,
  ],
  BILLING: [
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.BILLING_REFUND,
  ],
} as const;

/**
 * Check if permission is in a group
 */
export function isPermissionInGroup(
  permission: Permission,
  group: keyof typeof PERMISSION_GROUPS
): boolean {
  return (PERMISSION_GROUPS[group] as readonly Permission[]).includes(permission);
}
