// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwufulzthoqrwbwtvogx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dWZ1bHp0aG9xcndid3R2b2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjA5NzMsImV4cCI6MjA3MjI5Njk3M30.uO5bo6elt4LdAL0ULyIMQtaxnXAnfZRhIK8UqApm5B8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});