// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config } from '@/config/environments';

const SUPABASE_URL = config.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = config.supabaseKey;

// Validate configuration but don't throw during module initialization
// This allows the app to load and show a proper error message
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '❌ CRITICAL: Supabase configuration is missing!\n' +
    'Please ensure these environment variables are set:\n' +
    '  - VITE_SUPABASE_URL\n' +
    '  - VITE_SUPABASE_PUBLISHABLE_KEY\n\n' +
    'Current values:\n' +
    `  VITE_SUPABASE_URL: ${SUPABASE_URL || '(not set)'}\n` +
    `  VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY ? '(set)' : '(not set)'}`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with fallback values to prevent crash
// If config is missing, API calls will fail gracefully instead of crashing on load
export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Export validation function for runtime checks
export const isSupabaseConfigured = () => {
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY &&
    SUPABASE_URL !== 'https://placeholder.supabase.co' &&
    SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key'
  );
};